apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web # Make sure this matches your web deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31720 # Use this to access K8s Frontend via localhost:31720
