apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-web
        image: nathanle056/bracket-frontend:v17  # <--- Double check this image name!
        ports:
        - containerPort: 80