apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend    # Make sure this matches your frontend deployment label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31720 # Use this to access K8s Frontend via localhost:31720